// Code generated by mojo. DO NOT EDIT.
// Rerunning mojo will overwrite this file.

package files

import (
	"unsafe"

	jsoniter "github.com/json-iterator/go"
	"github.com/mojo-lang/core/go/pkg/mojo/core"
)

func init() {
	core.RegisterJSONTypeDecoder("files.GetFilesResponse", &GetFilesResponseCodec{})
	core.RegisterJSONTypeEncoder("files.GetFilesResponse", &GetFilesResponseCodec{})
}

type GetFilesResponseCodec struct {
}

func (codec *GetFilesResponseCodec) Decode(ptr unsafe.Pointer, iter *jsoniter.Iterator) {
	any := iter.ReadAny()
	getFilesResponse := (*GetFilesResponse)(ptr)
	if any.ValueType() == jsoniter.ArrayValue {
		any.ToVal(&getFilesResponse.Files)
	}
}

func (codec *GetFilesResponseCodec) IsEmpty(ptr unsafe.Pointer) bool {
	getFilesResponse := (*GetFilesResponse)(ptr)
	return getFilesResponse == nil || len(getFilesResponse.Files) == 0
}

func (codec *GetFilesResponseCodec) Encode(ptr unsafe.Pointer, stream *jsoniter.Stream) {
	getFilesResponse := (*GetFilesResponse)(ptr)
	if len(getFilesResponse.Files) > 0 {
		stream.WriteVal(getFilesResponse.Files)
	}
}
